# -*- coding: utf-8 -*-
"""classificazione_frasi_con_BERT_transformers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HodgG2Mw7DuKOj8SYcIEQCviMHMnxeeJ
"""

!pip install transformers
!pip install torch

import torch
from transformers import BertTokenizer, BertForSequenceClassification

#carica tokenizzatore e BERT
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForSequenceClassification.from_pretrained("bert-base-uncased")

#prendiamo la frase come input
def encode_sentence(sentence):
    input_ids = torch.tensor(tokenizer.encode(sentence, add_special_tokens=True)).unsqueeze(0)
    return input_ids

input_ids = encode_sentence("Ma quand'è che avete cominciato a essere così deludenti? Perché siete così assertivi? Ma pensate a mangiare e a bevere, che è l'unica cosa che sapite fa'")

#classifichiamo la frase
with torch.no_grad():
    outputs = model(input_ids)
    prediction = torch.argmax(outputs[0]).item()

if prediction == 1:
    print("Positive review")
else:
    print("Negative review")